replicaCount: 1

image:
  repository: ottomen
  tag: "v.1.0.0-cca475c"
  arch: windows-x64 #I have this tag in Docker registry

service:
  type: ClusterIP
  port: 8080

secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"

securityContext:
  privileged: true
