replicaCount: 1
image:
  repository: ottomen
  tag: "v.1.0.0-0535d13"
  arch: linux/amd64
service:
  type: ClusterIP
  port: 8080
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
