name: KBOT-CICD

on: push

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: make test
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push to ghcr.io
        run: make image-linux push-linux
        env:
          REGISTRY: ghcr.io
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Package HELM chart
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' kbot/values.yaml
    env:
      VERSION: ${{ env.VERSION }}
