name: KBOT-CICD

on: push

jobs: 
  ci: 
    name: CI
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run lint
        run: make lint  
      - name: Run tests
        run: make test
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 